import { TokenRefresher } from '@/auth/TokenRefresher';
import { LanguageProvider } from '@/language';
import { ReactQueryClientProvider } from '@/react-query';
import { AppRoutesProvider } from '@/routes';
import ThemeProvider from '@/styles/ThemeProvider';
import type { Metadata } from 'next';
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <AppRoutesProvider>
          <ThemeProvider>
            <LanguageProvider>
              <ReactQueryClientProvider>
                <TokenRefresher>{children}</TokenRefresher>
              </ReactQueryClientProvider>
            </LanguageProvider>
          </ThemeProvider>
        </AppRoutesProvider>
      </body>
    </html>
  );
}
